### ISSUE TITLE
Cannot assign null to property Spatie\MailcoachSdk\Resources\EmailList::$campaignMailer of type string

### ISSUE THREAD

**Issue by ToddSmithSalter** [spatie/mailcoach-sdk-php#7]
First off, Spatie team, thank you so much for your contribution to the php and Laravel communities.

I get this issue whenever I try to instantiate an email list to get a subscriber. In my use case, I am checking if the email is already subscribed to the list before sending the subscribe command.

I've debugged my app down to substituting parameters with raw strings with the same results. Wondering if this is an issue with was is being returned from mailcoach.cloud API?

https://flareapp.io/share/xPQ9JgrP#F85

**Comment by freekmurze** [comment]
Thanks for reporting this. We've made a change in our sdk and published it as v1.0.4

Run "composer update" to pull it in 👍
