### ISSUE TITLE
ManagesSubscribers shouldn't get ['data']

### ISSUE THREAD

**Issue by eele94** [spatie/mailcoach-sdk-php#9]
Default is not working for me.

In Tinker
`Spatie\Newsletter\Facades\Newsletter::subscribe('example@user.com');`

`WARNING  Undefined array key "data" in vendor/spatie/mailcoach-sdk-php/src/Actions/ManagesSubscribers.php on line 34.`

When I remove the ['data'] in the ManagesSubscribers.php it works.

 ```
   public function createSubscriber(string $emailListUuid, array $attributes): Subscriber
    {
        $attributes = $this->post("email-lists/{$emailListUuid}/subscribers", $attributes); // working
        // $attributes = $this->post("email-lists/{$emailListUuid}/subscribers", $attributes)['data']; // will return null

        return new Subscriber($attributes, $this);
    }
```

I have the latest versions.
"spatie/laravel-mailcoach": "^6.0", "spatie/laravel-newsletter": "^5.1",

In the browser through a controller the request is waiting infinitely.

selfhosted
Tried using a new laravel app with jetstream inertia scaffolding

**Comment by freekmurze** [comment]
I did a check, and it all seems be working as expected using the latest versions.

![CleanShot 2023-02-09 at 14 58 59@2x](https://user-images.githubusercontent.com/483853/217833214-e031feb4-0f76-4a57-b7ff-ee7cf5079c7f.jpg)

**Comment by eele94** [comment]
@freekmurze thanks for the quick reply..
I found out I have 2 issues.
- you're right and ['data'] issue is probably something from my own app.
- requests keeps hanging from 127.0.0.1:8000 subscribe -> to same server 127.0.0.1:8000 mailcoach

If I run php artisan serve twice and try to execute from 8001 to endpoint on 8000 it is working.
myapp Newsletter::subscribes 127.0.0.1:8001 -> standalone mailcoach example app 127.0.0.8000

My goal is to install mailcoach in my existing project and that one doesn't work.

```
NEWSLETTER_API_KEY="2|hMTUxo0n0aGgUryQrzi1D7X1qWhUjcfHC9BrO9eP"
NEWSLETTER_ENDPOINT="localhost:8000/api"
NEWSLETTER_LIST_ID="d56754b3-ee32-4556-95c3-1b369f5ed07a"

MAILCOACH_API_TOKEN="2|hMTUxo0n0aGgUryQrzi1D7X1qWhUjcfHC9BrO9eP"
MAILCOACH_API_ENDPOINT="localhost:8000/api"
```

When I try to connect with mailcoach from the same project it hangs (clean standalone mailcoach app with 1 route to test the subscribe function).

In the example you tried, did you installed in your own example application and it worked from the browser (not tinker)?

**Comment by eele94** [comment]
2nd problem wasn't working for me because I was testing it with php artisan serve (this only handles 1 request at a time).
When changing dev environment to nginx the request worked :)
Took me way to long to figure this out xD

Now I only have to find out why ['data'] is missing for me.
